### ISSUE TITLE
Release date?

### ISSUE THREAD

**Issue by RoyChaudhuri** [bioinform/metasv#1]
Hi, I enjoyed your talk at UKGS, where it was stated that the software would be released in "a couple of weeks". Please could you clarify when we can expect MetaSV to be released? I'm looking forward to trying it with my datasets.

**Comment by marghoob** [comment]
Hi @RoyChaudhuri , MetaSV is released now. Please give it a try when you get a chance. And feel free to file issues you encounter in the process. Thanks.
