### ISSUE TITLE
Error while reading AGE output

### ISSUE THREAD

**Issue by wjaratlerdsiri** [bioinform/metasv#104]
Hi,

I have used Version 0.4 and seen the error below. Do you fix this in version 0.5? 

INFO 2016-02-14 17:11:46,150 run_age_single-<Process(PoolWorker-10, started daemon)> Writing the ref sequence for region chr1.1076464.1076874
INFO 2016-02-14 17:11:46,151 run_age_single-<Process(PoolWorker-10, started daemon)> Processing 13 contigs for region (chr1, 1076464, chr1, 1076874)
INFO 2016-02-14 17:11:46,151 run_age_single-<Process(PoolWorker-10, started daemon)> Writing the assembeled sequence chr1_1076464_1076874_INS_0_NODE_1_length_1122_cov_20.4015_ID_295 of length 1122
INFO 2016-02-14 17:11:46,157 run_age_single-<Process(PoolWorker-10, started daemon)> Running /BCBIOMETASV/MINICONDA/METASV27JAN/AGE_ALIGN with arguments ['-indel', '-both', '-go=-6', '/bcbiometasv/miniconda/metasv27jan/UP53input/age/chr1.1076464.1076874.ref.fa', '/bcbiometasv/miniconda/metasv27jan/UP53input/age/0df25e19515155dfddbed3a8c720a98a.as.fa']
INFO 2016-02-14 17:11:46,199 run_age_single-<Process(PoolWorker-9, started daemon)> Will process 589 intervals
INFO 2016-02-14 17:11:46,218 run_age_single-<Process(PoolWorker-9, started daemon)> Matching interval chr1	1180324	1180344	eyJOVU1fU1ZNRVRIT0RTIjogMSwgIk5VTV9TVlRPT0xTIjogMSwgIlNDX0NPVkVSQUdFIjogIjQxOCIsICJTT1VSQ0VTIjogImNocjEtMTE3OTgyNC1jaHIxLTExODA4NDQtMC1Tb2Z0Q2xpcCIsICJTQ19ORUlHSF9TVVBQT1JUIjogIjQxIiwgIlNDX1JFQURfU1VQUE9SVCI6ICIzIiwgIlNDX0NIUjJfU1RSIjogImNocjE7NDsxMTgwMDI4OzExODA0MjgsLTE7NDstMTs3MixjaHIyOzMyOzMzMTQxMjk5OzMzMTQxNjY4LGNocjE1OzE7ODgwNzA1MzQ7ODgwNzA2MDcifQ==,INS,0,SC	1	.

INFO 2016-02-14 17:11:46,229 run_age_single-<Process(PoolWorker-9, started daemon)> Writing the ref sequence for region chr1.1180324.1180344
INFO 2016-02-14 17:11:46,231 run_age_single-<Process(PoolWorker-9, started daemon)> Processing 3 contigs for region (chr1, 1180324, chr1, 1180344)
INFO 2016-02-14 17:11:46,231 run_age_single-<Process(PoolWorker-9, started daemon)> Writing the assembeled sequence chr1_1180324_1180344_INS_0_NODE_1_length_1095_cov_19.8838_ID_63 of length 1095
INFO 2016-02-14 17:11:46,234 run_age_single-<Process(PoolWorker-9, started daemon)> Running /BCBIOMETASV/MINICONDA/METASV27JAN/AGE_ALIGN with arguments ['-indel', '-both', '-go=-6', '/bcbiometasv/miniconda/metasv27jan/UP53input/age/chr1.1180324.1180344.ref.fa', '/bcbiometasv/miniconda/metasv27jan/UP53input/age/3e23e83081dd0bbc7bc0548bbb1e4534.as.fa']
INFO 2016-02-14 17:11:46,269 run_age_single-<Process(PoolWorker-10, started daemon)> Returned code 0 (0.0812719 seconds)
ERROR 2016-02-14 17:11:46,271 run_age_single-<Process(PoolWorker-10, started daemon)> Caught exception in worker thread
Traceback (most recent call last):
  File "/bcbiometasv/miniconda/metasv27jan/metasv/run_age.py", line 146, in run_age_single
    age_record = AgeRecord(out,tr_region_1=tr_region)
  File "/bcbiometasv/miniconda/metasv27jan/metasv/age_parser.py", line 85, in __init__
INFO 2016-02-14 17:11:46,295 run_age_single-<Process(PoolWorker-9, started daemon)> Returned code 0 (0.04352 seconds)
ERROR 2016-02-14 17:11:46,296 run_age_single-<Process(PoolWorker-9, started daemon)> Caught exception in worker thread
Traceback (most recent call last):
  File "/bcbiometasv/miniconda/metasv27jan/metasv/run_age.py", line 146, in run_age_single
    age_record = AgeRecord(out,tr_region_1=tr_region)
  File "/bcbiometasv/miniconda/metasv27jan/metasv/age_parser.py", line 85, in __init__
    self.read_from_age_file(age_out_file)
  File "/bcbiometasv/miniconda/metasv27jan/metasv/age_parser.py", line 186, in read_from_age_file
    file2, len2 = self.parse_input_descriptor(age_fd)
  File "/bcbiometasv/miniconda/metasv27jan/metasv/age_parser.py", line 126, in parse_input_descriptor
    raise AgeFormatError("INPUT DESCRIPTOR", age_fd.line_num)
    self.read_from_age_file(age_out_file)
  File "/bcbiometasv/miniconda/metasv27jan/metasv/age_parser.py", line 186, in read_from_age_file
AgeFormatError: Error while reading AGE output, L13 (section INPUT DESCRIPTOR).
    file2, len2 = self.parse_input_descriptor(age_fd)
  File "/bcbiometasv/miniconda/metasv27jan/metasv/age_parser.py", line 126, in parse_input_descriptor
    raise AgeFormatError("INPUT DESCRIPTOR", age_fd.line_num)
AgeFormatError: Error while reading AGE output, L13 (section INPUT DESCRIPTOR).
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/bcbiometasv/miniconda/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/bcbiometasv/miniconda/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/bcbiometasv/miniconda/lib/python2.7/multiprocessing/pool.py", line 389, in _handle_results
    task = get()
TypeError: ('__init__() takes exactly 3 arguments (1 given)', <class 'metasv.age_parser.AgeFormatError'>, ())

James

**Comment by marghoob** [comment]
Hi James

This issue should be resolved in 0.5. Please make sure you build AGE from
the main repository (https://github.com/abyzovlab/AGE) with OMP support
disabled using "make OMP=no"

Thanks
Marghoob.

**Comment by wjaratlerdsiri** [comment]
Thankyou Marghoob. Now AGE is working fine.

James

**Comment by gulfemd** [comment]
Hi, 

I have a similar situation, although I am using meta-sv version 0.5.4 and age version 0.4.
It would be great if you can look at it!
Thanks,

INFO 2017-05-18 15:40:54,066 run_age_single-<Process(PoolWorker-23, started daemon)> Matching interval chr20	5041941	5042942	eyJOVU1fU1ZNRVRIT0RTIjogMSwgIk5VTV9TVlRPT0xTIjogMSwgIlNDX0xPQ0FUSU9OUyI6ICI1MDQyNDQxLDUwNDI0NDIiLCAiU0NfQ09WRVJBR0UiOiAiMjc5IiwgIlNPVVJDRVMiOiAiY2hyMjAtNTA0MTk0MS1jaHIyMC01MDQyOTQyLTAtU29mdENsaXAiLCAiU0NfTkVJR0hfU1VQUE9SVCI6ICIzMiIsICJTQ19SRUFEX1NVUFBPUlQiOiAiMTAiLCAiU0NfQ0hSMl9TVFIiOiAiY2hyNzsxOzc1MTUwNzYyOzc1MTUwODM3LGNocjQ7MTs1NTU5MzE3NTs1NTU5MzI1MCxjaHIxNTs4OzQxMzk5MzMxOzQxMzk5NDI1LGNocjk7MTsxMzI3MTE3NjM7MTMyNzExODM4LGNocjg7MTs5OTI5OTEwMjs5OTI5OTE3NyxjaHIxMTsxOzEwMzEwMjIzMjsxMDMxMDIzMDcsY2hyMTc7MTA7MzEyNDg2Mjk7ODAyOTc0MDMsY2hyMjA7OTs1MDQyMzU4OzUwNDI1MTYifQ==,INS,0,SC	1	.

INFO 2017-05-18 15:40:54,067 run_age_single-<Process(PoolWorker-17, started daemon)> Writing the ref sequence for region chr20.1400210.1403153
INFO 2017-05-18 15:40:54,068 run_age_single-<Process(PoolWorker-17, started daemon)> Processing 3 contigs for region (chr20, 1400210, chr20, 1403153)
INFO 2017-05-18 15:40:54,068 run_age_single-<Process(PoolWorker-17, started daemon)> Writing the assembeled sequence chr20_1400210_1403153_DUP_0_NODE_1_length_4833_cov_12.577 of length 4833
INFO 2017-05-18 15:40:54,069 run_age_single-<Process(PoolWorker-17, started daemon)> Running /ROOT/MINICONDA2/BIN/AGE_ALIGN with arguments ['-tdup', '-both', '-go=-6', 'meta-work/age/chr20.1400210.1403153.ref.fa', 'meta-work/age/bb25c1d3cb7ee2197ca780f69bcd243d.as.fa']
INFO 2017-05-18 15:40:54,072 run_age_single-<Process(PoolWorker-23, started daemon)> Writing the ref sequence for region chr20.5041941.5042942
INFO 2017-05-18 15:40:54,072 run_age_single-<Process(PoolWorker-23, started daemon)> Processing 2 contigs for region (chr20, 5041941, chr20, 5042942)
INFO 2017-05-18 15:40:54,072 run_age_single-<Process(PoolWorker-23, started daemon)> Writing the assembeled sequence chr20_5041941_5042942_INS_0_NODE_1_length_3022_cov_13.9803 of length 3022
INFO 2017-05-18 15:40:54,073 run_age_single-<Process(PoolWorker-23, started daemon)> Running /ROOT/MINICONDA2/BIN/AGE_ALIGN with arguments ['-indel', '-both', '-go=-6', 'meta-work/age/chr20.5041941.5042942.ref.fa', 'meta-work/age/83201bf1723b345fba5cfa9df2ac45fc.as.fa']
INFO 2017-05-18 15:40:54,412 run_age_single-<Process(PoolWorker-21, started daemon)> Returned code 0 (0.332866 seconds)
ERROR 2017-05-18 15:40:54,413 run_age_single-<Process(PoolWorker-21, started daemon)> Caught exception in worker thread
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/metasv/age.py", line 146, in run_age_single
    age_record = AgeRecord(out,tr_region_1=tr_region)
  File "/usr/local/lib/python2.7/dist-packages/metasv/age_parser.py", line 88, in __init__
    self.read_from_age_file(age_out_file)
  File "/usr/local/lib/python2.7/dist-packages/metasv/age_parser.py", line 189, in read_from_age_file
    file2, len2 = self.parse_input_descriptor(age_fd)
  File "/usr/local/lib/python2.7/dist-packages/metasv/age_parser.py", line 129, in parse_input_descriptor
    raise AgeFormatError("INPUT DESCRIPTOR", age_fd.line_num)
AgeFormatError: Error while reading AGE output, L13 (section INPUT DESCRIPTOR).
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 389, in _handle_results
    task = get()
TypeError: ('__init__() takes exactly 3 arguments (1 given)', <class 'metasv.age_parser.AgeFormatError'>, ())

**Comment by marghoob** [comment]
Hi @gulfemd can you attach the AGE output file in question? We can check against the current output format for AGE to see the problem.
