### ISSUE TITLE
example command

### ISSUE THREAD

**Issue by boboppie** [bioinform/metasv#37]
Dear developers,

Thank you for contributing the tool to the community.

At the moment, I have ref and bam files, and when I run:

```
run_metasv.py --sample sample_A --reference ./ref/ref.fasta --bam ./bam/sample_A.bam --outdir ./out
```
I got an error - "Nothing to do since no SV file specified".

Could you please let me know where goes wrong? And what's the best way to run the tool? Could you show me an example?

Best wishes,
Fengyuan

**Comment by boboppie** [comment]
In addition to metasv, I've installed bedtools/2.23.0, SPAdes/3.5.0 and AGE-simple-parseable-output

**Comment by marghoob** [comment]
Hi @boboppie , thanks for your interest in MetaSV and your suggestion. At the moment, the SV tools need to be run separately and their output files needs to be passed to MetaSV using command-line options. For example, CNVnator output files can be passed as --cnvnator_native <file1> <file2> .... Similarly, there is --pindel_native, breakdancer_native and --breakseq_native. By native, it is meant the raw output of these tools (these are not VCF files). You can try out the small test in https://github.com/bioinform/metasv/blob/master/test/test_run.sh by the way.

**Comment by boboppie** [comment]
Thank you for the instruction @marghoob
