### ISSUE TITLE
Is metasv compatible with breakseq2? 

### ISSUE THREAD

**Issue by boboppie** [bioinform/metasv#38]
Hi @marghoob，

I just noticed breakseq2 repo. Can I replace (old) breakseq with  breakseq2 output as input for metasv?

Best wishes,
Fengyuan

**Comment by marghoob** [comment]
Hi @boboppie ,

MetaSV is compatible with BreakSeq2. In fact, for our paper, we used BreakSeq2. You should try to use the native GFF output of BreakSeq2 as an input to MetaSV. 

Regards,
Marghoob.
