### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by boboppie** [bioinform/metasv#40]
Hi @marghoob ,

I've got an error as following, could you advise me on a fix? 

```
Traceback (most recent call last):
  File "/home/cbrcmod/scratch/modules/out/modulebin/metasv/0.3/bin/run_metasv.py", line 108, in <module>
    stop_spades_on_fail=args.stop_spades_on_fail, gt_window=args.gt_window, gt_normal_frac=args.gt_normal_frac, isize_mean=args.isize_mean, isize_sd=args.isize_sd, extraction_max_read_pairs=args.extraction_max_read_pairs))
  File "/home/cbrcmod/scratch/modules/out/modulebin/metasv/0.3/lib/python2.7/site-packages/metasv/main.py", line 295, in run_metasv
    pybedtools.BedTool(bed_intervals).saveas(merged_bed)
  File "/home/cbrcmod/scratch/modules/out/modulebin/metasv/0.3/lib/python2.7/site-packages/pybedtools/bedtool.py", line 390, in __init__
    fn = BedTool(iter(fn)).saveas().fn
  File "/home/cbrcmod/scratch/modules/out/modulebin/metasv/0.3/lib/python2.7/site-packages/pybedtools/bedtool.py", line 668, in decorated
    result = method(self, *args, **kwargs)
  File "/home/cbrcmod/scratch/modules/out/modulebin/metasv/0.3/lib/python2.7/site-packages/pybedtools/bedtool.py", line 2729, in saveas
    fn = self._collapse(self, fn=fn, trackline=trackline)
  File "/home/cbrcmod/scratch/modules/out/modulebin/metasv/0.3/lib/python2.7/site-packages/pybedtools/bedtool.py", line 1097, in _collapse
    for i in iterable:
  File "pybedtools/cbedtools.pyx", line 638, in pybedtools.cbedtools.IntervalIterator.__next__ (pybedtools/cbedtools.cpp:9096)
MemoryError
```

Best wishes,
Fengyuan

**Comment by marghoob** [comment]
This looks like a pybedtools issue. How much memory does your machine have? I'd strongly advise on testing it on a 64GB RAM machine or more. It would also be good to check the peak memory usage of MetaSV to identify if it uses a lot of memory before crashing.

**Comment by boboppie** [comment]
@marghoob Thanks for the suggestion!

I've swiched to a higher memory machine and now it gave me a different error:

```
File "/home/cbrcmod/scratch/modules/out/modulebin/metasv/0.3/lib/python2.7/site-packages/pybedtools/bedtool.py", line 1097, in _collapse
    for i in iterable:
  File "pybedtools/cbedtools.pyx", line 680, in pybedtools.cbedtools.IntervalFile.__next__ (pybedtools/cbedtools.cpp:9605)
pybedtools.cbedtools.MalformedBedLineError: malformed line: ['1', '62391141', '117786', 'eyJCRF9TQ09SRSI6IDk5LjAsICJCRF9PUkkyIjogIjEwNDArMTAyOS0iLCAiQkRfUE9TMSI6IDYyMzkxMTQwLCAiQkRfUE9TMiI6IDExNzc4NiwgIkJEX09SSTEiOiAiMTg5KzU0LSIsICJCRF9DSFIxIjogIjEiLCAiQkRfQ0hSMiI6ICJHTDAwMDIyMC4xIiwgIkJEX1NVUFBPUlRJTkdfUkVBRF9QQUlSUyI6IDMyMn0=,DEL,424,RP', '1', '.']
```

chr end is smaller than start? How can I figure out where it comes from?

Best wishes,
Fengyuan

**Comment by marghoob** [comment]
Is it possible for you to send me the BED files and the input files for
your MetaSV run? You can find the intermediate BED files in the MetaSV work
directory. It would also be helpful to send me the lines in MetaSV python
scripts where the error occurred. The line in question, in your error
message, seems very wrong with respect to the end coordinate.


On Fri, May 29, 2015 at 8:13 AM, Fengyuan Hu <notifications@github.com>
wrote:

> @marghoob <https://github.com/marghoob> Thanks for the suggestion!
>
> I've swiched to a higher memory machine and now it gave me a different
> error:
>
> File "/home/cbrcmod/scratch/modules/out/modulebin/metasv/0.3/lib/python2.7/site-packages/pybedtools/bedtool.py", line 1097, in _collapse
>     for i in iterable:
>   File "pybedtools/cbedtools.pyx", line 680, in pybedtools.cbedtools.IntervalFile.__next__ (pybedtools/cbedtools.cpp:9605)
> pybedtools.cbedtools.MalformedBedLineError: malformed line: ['1', '62391141', '117786', 'eyJCRF9TQ09SRSI6IDk5LjAsICJCRF9PUkkyIjogIjEwNDArMTAyOS0iLCAiQkRfUE9TMSI6IDYyMzkxMTQwLCAiQkRfUE9TMiI6IDExNzc4NiwgIkJEX09SSTEiOiAiMTg5KzU0LSIsICJCRF9DSFIxIjogIjEiLCAiQkRfQ0hSMiI6ICJHTDAwMDIyMC4xIiwgIkJEX1NVUFBPUlRJTkdfUkVBRF9QQUlSUyI6IDMyMn0=,DEL,424,RP', '1', '.']
>
> chr end is smaller than start? How can I figure out where it comes from?
>
> Best wishes,
> Fengyuan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bioinform/metasv/issues/40#issuecomment-106842455>.
>



-- 

<http://www.bina.com>

*Marghoob Mohiyuddin, PhD  *//  Sr. Bioinformatics Scientist, Bina
Technologies, part of Roche Sequencing
E. marghoob@bina.com

*Learn More*  //  video <http://www.bina.com/product.html>  //  news
<http://www.bina.com/press-coverage.html>  //  posters
<http://f1000.com/posters/search?query=bina+technologies>  //  science
<http://www.bina.com/science.html>  //  platform
<http://www.bina.com/platform.html>
*Test Drive Bina  //  Experience NextGen analysis for yourself *
<http://www.bina.com/test-drive.html>

**Comment by marghoob** [comment]
Okay from the input files you sent me, it appears that the BreakDancer file is malformed. The file input/M42KJ.breakdancer.max has the following line:
`1       62391140        189+54- GL000220.1      117786  1040+1029-      DEL     424     99      322     /scratch/cbrc/tmp/fh293/cnv-WGS/bam/M42KJ_A.bam|322     -94.63` which is incorrect since a DEL entry should have chr1 and chr2 the same, while here chr1=1 and chr2-GL000220.1. You should clean up the BreakDancer output file by removing all ITX and CTX lines as well as other lines where chr1 is not the same as chr2. And then try running again.

**Comment by boboppie** [comment]
@marghoob Thank you so much for looking into this. So this is a bug in BreakDancer? Have you seen such bad lines before?

**Comment by marghoob** [comment]
If your breakdancer file was the raw output of BreakDancer then this is
definitely a bug in BreakDancer. You should file an issue with them. I have
not seen bad lines with BreakDancer 1.4.5 but then I have also not run
BreakDancer with the -t option to detect transchromosomal rearrangements.

On Thu, Jun 4, 2015 at 7:38 AM, Fengyuan Hu <notifications@github.com>
wrote:

> @marghoob <https://github.com/marghoob> Thank you so much for looking
> into this. So this is a bug in BreakDancer? Have you seen such bad lines
> before?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bioinform/metasv/issues/40#issuecomment-108917954>.
>



-- 

<http://www.bina.com>

*Marghoob Mohiyuddin, PhD  *//  Sr. Bioinformatics Scientist, Bina
Technologies, part of Roche Sequencing
E. marghoob@bina.com

*Learn More*  //  video <http://www.bina.com/product.html>  //  news
<http://www.bina.com/press-coverage.html>  //  posters
<http://f1000.com/posters/search?query=bina+technologies>  //  science
<http://www.bina.com/science.html>  //  platform
<http://www.bina.com/platform.html>
*Test Drive Bina  //  Experience NextGen analysis for yourself *
<http://www.bina.com/test-drive.html>

**Comment by marghoob** [comment]
@boboppie by the way, I have updated MetaSV to ignore BreakDancer lines which are bad. If you install MetaSV as `pip install https://github.com/bioinform/metasv/archive/master.zip`, then it should have the fix.
