### ISSUE TITLE
Reference file not indexed

### ISSUE THREAD

**Issue by Madelinehazel** [bioinform/metasv#87]
When I run metaSV, I get the following error: Reference file hg19_reference/hg19_multifasta is not indexed
What kind of indexing does the reference fasta file need? 

Thank you, 
Madeline

**Comment by johnmu** [comment]
See http://www.htslib.org/doc/samtools.html and look for faidx. This generates an index of the fasta file so that it can be easily seeked.

**Comment by Madelinehazel** [comment]
That's interesting, I already generated a fa.fai index file with faidx. It's in the same folder as the the multifasta file. I'm not sure what the issue is, then. 
Thank you for your rapid reply!

**Comment by johnmu** [comment]
Can you paste a listing of the contents of the directory that contains your reference  hg19_reference/hg19_multifasta?

**Comment by Madelinehazel** [comment]
Ah, I identified the problem- an error in the file name. Sorry about that!

**Comment by johnmu** [comment]
No worries!
