### ISSUE TITLE
No such file or directory: 'cnvnator.call'

### ISSUE THREAD

**Issue by Madelinehazel** [bioinform/metasv#88]
Hello, 

When I use the following command: 
run_metasv.py --reference hg19_reference/hg19_multifasta.fa --boost_ins --breakdancer_native breakdancer.out --breakseq_native breakseq.gff --cnvnator_native cnvnator.call --pindel_native pindel_D pindel_LI pindel_SI pindel_TD pindel_INV --sample A10890 --bam A10890_C1VBNACXX_1.bam --spades SPAdes-3.6.2-Linux/bin/spades.py --age AGE-simple-parseable-output/age_align.cpp --num_threads 15 --workdir work --outdir out --min_ins_support 2 --max_ins_intervals 500000 --isize_mean 500 --isize_sd 150

I get the following output and error message:
INFO 2016-01-20 10:56:47,410 metasv.main          Only SVs on the following contigs will be reported: ['chr1', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr2', 'chr20', 'chr21', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chrM', 'chrX', 'chrY']
INFO 2016-01-20 10:56:47,410 metasv.main          Load native files
INFO 2016-01-20 10:56:47,410 metasv.cnvnator_reader File is cnvnator.call
Traceback (most recent call last):
  File "/usr/local/bin/run_metasv.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/hpcuser01/metasv-0.3/scripts/run_metasv.py", line 108, in <module>
    stop_spades_on_fail=args.stop_spades_on_fail, gt_window=args.gt_window, gt_normal_frac=args.gt_normal_frac, isize_mean=args.isize_mean, isize_sd=args.isize_sd, extraction_max_read_pairs=args.extraction_max_read_pairs))
  File "/home/hpcuser01/metasv-0.3/metasv/main.py", line 130, in run_metasv
    for record in svReader(native_file):
  File "/home/hpcuser01/metasv-0.3/metasv/cnvnator_reader.py", line 106, in __init__
    self.file_fd = open(file_name)
IOError: [Errno 2] No such file or directory: 'cnvnator.call'

I am not sure why. Help would be appreciated!

Thank you, 
Madeline

**Comment by marghoob** [comment]
Hi Madeline

Did you check for the existence of cnvnator.call file in the directory where you invoke run_metasv?

Marghoob

**Comment by Madelinehazel** [comment]
I see a cnvnator_reader.py under the metasv directory but not a cnvnator.call file

**Comment by marghoob** [comment]
cnvnator.call file is an input file to be provided by the user. It should be a file generated by running CNVnator. In case CNVnator was not run, you can omit the --cnvnator_native option.
