### ISSUE TITLE
Independently download BreakSeq, Breakdancer, Pindel, CNVnator

### ISSUE THREAD

**Issue by Madelinehazel** [bioinform/metasv#92]
Hi team,
Does metaSV support the four SV callers, or do I have to install those and run them separately?
Thanks, 
Madeline
(Bioinformagician)

**Comment by marghoob** [comment]
Hi Madeine

You will need to install and run the SV callers separately. MetaSV can then be invoked on the output of the SV callers run to get a set of much better quality calls.

Hope that helps.
