### ISSUE TITLE
Request to specify one kmer for local SPADES assembly

### ISSUE THREAD

**Issue by wjaratlerdsiri** [bioinform/metasv#93]
Hello MetaSV Team,

I have used version 0.4 and seen 3 kmer values used to refine each SV. Is it possible to have options to use only one kmer per SV?

I know kmers need to be optimised, but I think users have prior knowledge of their reads, such as read length. So, they can reasonably choose a certain kmer in MetaSV to use so as to save computation.

Any thoughts? Thank you for this very great program.

Regards,
James

**Comment by marghoob** [comment]
Good suggestion. We will add something like "--spades_options" to specify additional options to SPAdes during local assembly.

**Comment by wjaratlerdsiri** [comment]
COOL!

James

**Comment by marghoob** [comment]
Fixed in #94
